import pino from "pino";

export const LOG_REDACT_PATHS = [
  "password",
  "passwordHash",
  "accessToken",
  "refreshToken",
  "access_token",
  "refresh_token",
  "token",
  "authorization",
  "cookie",
  "OPENAI_API_KEY",
  "apiKey",
  "client_secret",
  "client_key",
  "ENCRYPTION_KEY",
  "SMTP_PASSWORD",
  "tokenCipher",
  "rawToken",
  "verifyLoginToken",
  "S3_ACCESS_KEY_ID",
  "S3_SECRET_ACCESS_KEY",
  "REDIS_URL",
  "TIKTOK_CLIENT_SECRET",
  "META_APP_SECRET",
  "X_CLIENT_SECRET",
  "GOOGLE_CLIENT_SECRET",
  "YOUTUBE_CLIENT_SECRET",
  "AUTH_GOOGLE_SECRET",
  "AUTH_SECRET",
  "STRIPE_SECRET_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "DATABASE_URL",
  "UPLOAD_POST_API_KEY",
  "UPLOAD_POST_WEBHOOK_SECRET",
  "access_url",
  "accessUrl",
  "jwt",
  "*.accessTokenEncrypted",
  "*.refreshTokenEncrypted",
  "SMTP_USER",
  "signedUrl",
  "uploadUrl",
];

export const logger = pino({
  level: process.env.LOG_LEVEL ?? (process.env.NODE_ENV === "production" ? "info" : "debug"),
  redact: {
    paths: LOG_REDACT_PATHS,
    remove: true,
  },
});
